version: 2.1
orbs:
  docker: circleci/docker@2.2.0
  maven: circleci/maven@1.4.1
  snyk: snyk/snyk@1.4.0

executors:
  docker-executor:
    docker:
      - image: cimg/openjdk:17.0.7
        environment:
          NODE_VERSION: "14"  # Specify the Node.js version you want

jobs:
  ci:
    executor: docker-executor
    steps:
      - checkout

      # Restore dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline

      # Save dependencies for future runs
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Build the JAR file
      - run:
          name: Build JAR
          command: mvn package -DskipTests=true
          working_directory: 

      # Persist the JAR file in the workspace
      - persist_to_workspace:
          root: ./target/ProjectHarbourBooking-0.0.1-SNAPSHOT.jar
          paths:
            - ProjectHarbourBooking-0.0.1-SNAPSHOT.jar

      # Run Maven tests
      - run:
          name: Run Maven Test
          command: mvn test

      # # Authenticate with Snyk
      # - run:
      #     name: Authenticate with Snyk
      #     command: echo "$SNYK_TOKEN" | npx snyk auth
      
      # Run Snyk security scan
      # - run:
      #     name: Install Snyk
      #     command: npm install -g snyk --prefix=/home/circleci/.npm-global  # Install snyk globally
      # - run:
      #     name: Snyk Security Scan
      #     command: npx snyk test

  cd:
    executor: docker-executor
    steps:
      - checkout

      # Restore persisted JAR file from the workspace
      - attach_workspace:
          at: ./target/ProjectHarbourBooking-0.0.1-SNAPSHOT.jar

      # Install Docker for building and pushing the Docker image
      - setup_remote_docker

      # Build the Docker image with semantic control tags
      - run:
          name: Build Docker Image
          command: |
            docker build -t module04-project02:${CIRCLE_SHA1} -t module04-project02:latest .

      # Push the Docker image to a container registry (e.g., Docker Hub)
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push module04-project02:${CIRCLE_SHA1}
            docker push module04-project02:latest

  test_functionality_1:
    executor: docker-executor
    steps:
      - checkout
      # Add steps for testing functionality 1

  test_functionality_2:
    executor: docker-executor
    steps:
      - checkout
      # Add steps for testing functionality 2

  test_functionality_3:
    executor: docker-executor
    steps:
      - checkout
      # Add steps for testing functionality 3

workflows:
  version: 2
  ci_cd:
    jobs:
      - ci
      - cd:
          requires:
            - ci
          filters:
            branches:
              only: release
