version: 2.1
orbs:
  docker: circleci/docker@2.2.0
  snyk: snyk/snyk@1.7.0
  # heroku: circleci/heroku@2.0.0
jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run: mvn clean package
      - run: |
          echo “Running tests...”
          mvn test
  
  #Job to perform Snyk scan
  snyk_scan:
    docker:
      - image: cimg/openjdk:17.0.7
    environment:
      IMAGE_NAME: xxnlxzx/sctp-se-module04-java-devops-projectteam02 # Use lowercase repository name
    steps:
      - checkout
      - run: mvn clean package
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan: 
          docker-image-name: $IMAGE_NAME
  
  # Job to build the Docker image and push to DockerHub
  docker_build_and_push:
    # executor: docker/docker
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run: mvn clean package
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
            docker build -t ${DOCKER_LOGIN}/module04-project02:${CIRCLE_SHA1} .
            docker push ${DOCKER_LOGIN}/module04-project02:${CIRCLE_SHA1}
            

  # Deploy to Heroku
  deploy_to_heroku:
    #executor: docker/docker
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run: mvn clean package
      - setup_remote_docker
      - heroku/install
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku container:push web -a module04-project02
            heroku container:release web -a module04-project02
  #

workflows:
  ci_flow:
    jobs:
      - build_and_test:
          filters:
            branches:
              only: develop
      - snyk_scan:
          requires:
            - build_and_test
          filters:
            branches:
              only: develop

  cicd_flow:
    jobs:
      - docker_build_and_push:
          filters:
            branches:
              only: main
      # - deploy_to_heroku:
          requires:
            - docker_build_and_push
          filters:
            branches:
              only: main
