version: 2.1
orbs:
  docker: circleci/docker@2.2.0
  maven: circleci/maven@1.4.1
  snyk: snyk/snyk@1.7.0

jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run: mvn clean package
      - run:
          name: Running tests...
          command: mvn test

  cicd_flow:
    executor: docker-executor
    steps:
      # 1. Spin up environment
      - checkout

      # 2. Build JAR
      - run:
          name: Build JAR
          command: mvn package -DskipTests=true
          working_directory: /home/circleci/project  # Path to project

      # 3. Setup a remote Docker engine (optional, depending on your setup)
      - setup_remote_docker

      # 4. Build and Push Docker image
      - run:
          name: Build and Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
            docker build -t $DOCKER_LOGIN/module04-project02:$CIRCLE_SHA1 .
            docker push $DOCKER_LOGIN/module04-project02:$CIRCLE_SHA1

      # 5. Run Docker container (optional, you can skip this if not needed)
      - run:
          name: Run Docker Container
          command: |
            docker run -d -p 8000:8080 $DOCKER_LOGIN/module04-project02:$CIRCLE_SHA1

      # 6. Deploy and run the application on Heroku (adjust this step according to your deployment process)
      - run:
          name: Deploy to Heroku
          command: |
            # Add your deployment steps for Heroku here

workflows:
  version: 2
  cicd_flow:
    jobs:
      - build_and_test
      - cicd_flow:
          requires:
            - build_and_test
          filters:
            branches:
              only: develop
